/*
 * Copyright 2026 Julie Golston, Scaffold Studios
 * Licensed under the Apache License, Version 2.0.
 * See LICENSE and NOTICE files for full terms.
 */

/** CAST — Report Generator: JSON and Markdown outputs */

import { writeFileSync, mkdirSync } from 'fs';
import { resolve } from 'path';
import type { AggregatedReport, DeduplicatedFinding } from './types.js';

function ensureDir(dir: string) {
  mkdirSync(dir, { recursive: true });
}

export function writeJsonReport(report: AggregatedReport, outputDir: string): string {
  ensureDir(outputDir);
  const filePath = resolve(outputDir, 'cast-report.json');
  writeFileSync(filePath, JSON.stringify(report, null, 2));
  return filePath;
}

function severityEmoji(s: string): string {
  switch (s) {
    case 'CRITICAL': return '🔴';
    case 'HIGH': return '🟠';
    case 'MEDIUM': return '🟡';
    case 'LOW': return '🔵';
    case 'INFO': return '⚪';
    default: return '⚪';
  }
}

function findingBlock(f: DeduplicatedFinding, idx: number): string {
  return `### ${idx + 1}. ${severityEmoji(f.severity)} [${f.severity}] ${f.title}

**File**: \`${f.file}:${f.line}\`
**Category**: ${f.category}
**Reported by**: ${f.occurrences} agent(s) across ${f.squadsReporting.length} squad(s)
**Confidence**: ${Math.round(f.confidence * 100)}%

**Description**: ${f.description}

**Impact**: ${f.impact}

**Suggested Fix**: ${f.suggestedFix}

---
`;
}

export function writeMarkdownDashboard(report: AggregatedReport, outputDir: string): string {
  ensureDir(outputDir);

  const m = report.metadata;
  const findings = report.findings;

  // Severity counts
  const sevCounts: Record<string, number> = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0, INFO: 0 };
  for (const f of findings) {
    sevCounts[f.severity] = (sevCounts[f.severity] || 0) + 1;
  }

  // Category counts
  const catCounts: Record<string, number> = {};
  for (const f of findings) {
    catCounts[f.category] = (catCounts[f.category] || 0) + 1;
  }

  const md = `# CAST — Coordinated Agent Swarm Testing: Dashboard

**Framework**: ${m.framework} v${m.version}
**Timestamp**: ${m.timestamp}
**Model**: ${m.model}
**Target**: ${m.appName}

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Agents | ${m.totalAgents} |
| Successful | ${m.successfulAgents} |
| Failed | ${m.failedAgents} |
| Unique Findings | ${findings.length} |
| Total Cost | $${m.totalCost.toFixed(2)} |
| Total Tokens | ${(m.totalTokens.input + m.totalTokens.output).toLocaleString()} |
| Avg Latency | ${m.totalAgents > 0 ? Math.round(m.totalLatencyMs / m.totalAgents) : 0}ms |

---

## Findings by Severity

| Severity | Count |
|----------|-------|
| ${severityEmoji('CRITICAL')} CRITICAL | ${sevCounts.CRITICAL} |
| ${severityEmoji('HIGH')} HIGH | ${sevCounts.HIGH} |
| ${severityEmoji('MEDIUM')} MEDIUM | ${sevCounts.MEDIUM} |
| ${severityEmoji('LOW')} LOW | ${sevCounts.LOW} |
| ${severityEmoji('INFO')} INFO | ${sevCounts.INFO} |
| **Total** | **${findings.length}** |

---

## Findings by Category

| Category | Count |
|----------|-------|
${Object.entries(catCounts).sort((a, b) => b[1] - a[1]).map(([cat, count]) => `| ${cat} | ${count} |`).join('\n')}

---

## File Heatmap (Most Findings)

| File | Unique Findings |
|------|----------------|
${Object.entries(report.fileHeatmap).sort((a, b) => b[1] - a[1]).map(([file, count]) => `| \`${file}\` | ${count} |`).join('\n')}

---

## Squad Performance

${report.squadStats.map(s => `### Squad: ${s.squad}
| Metric | Value |
|--------|-------|
| Agents | ${s.agentCount} |
| Successful | ${s.successCount} |
| Total Findings | ${s.totalFindings} |
| Critical | ${s.bySeverity.CRITICAL} |
| High | ${s.bySeverity.HIGH} |
| Medium | ${s.bySeverity.MEDIUM} |
| Low | ${s.bySeverity.LOW} |
| Info | ${s.bySeverity.INFO} |
`).join('\n')}

---

## All Findings (sorted by severity)

${findings.map((f, i) => findingBlock(f, i)).join('\n')}

---

## Agent Details

${report.rawResults.map(r => `- **${r.agentId}** (${r.squad}) — ${r.persona}: ${r.findings.length} findings, ${r.tokenUsage.input + r.tokenUsage.output} tokens, ${r.latencyMs}ms`).join('\n')}

---

*Generated by CAST (cast-swarm) — Coordinated Agent Swarm Testing v${m.version}*
`;

  const filePath = resolve(outputDir, 'cast-dashboard.md');
  writeFileSync(filePath, md);
  return filePath;
}
